-- =========================================================
-- OoshDB schema (PostgreSQL 17+)
-- =========================================================
-- NOTE: run in a clean database or drop existing tables first.
--       Tables are created in dependency order.
-- =========================================================

-- ---------- Reference / lookup tables ----------
CREATE TABLE shops (
  shop_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_name    VARCHAR(50)  NOT NULL,
  suburb       VARCHAR(50),
  postcode     CHAR(4)      NOT NULL,
  state        CHAR(3)      NOT NULL
);

CREATE TABLE categories (
  category_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE payment_methods (
  payment_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_method_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE delivery_methods (
  delivery_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delivery_method_name VARCHAR(50) NOT NULL UNIQUE
);

-- ---------- Core entities ----------
CREATE TABLE customers (
  customer_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id       INTEGER NOT NULL
                   REFERENCES shops(shop_id)
                   ON UPDATE CASCADE ON DELETE RESTRICT,
  first_name    VARCHAR(50) NOT NULL,
  last_name     VARCHAR(50) NOT NULL,
  mobile        VARCHAR(20) UNIQUE,
  email         VARCHAR(120) UNIQUE,
  gender        VARCHAR(10) NOT NULL,
  date_of_birth DATE        NOT NULL,
  address       VARCHAR(200)
);

CREATE TABLE staff (
  staff_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id       INTEGER NOT NULL
                   REFERENCES shops(shop_id)
                   ON UPDATE CASCADE ON DELETE RESTRICT,
  first_name    VARCHAR(50) NOT NULL,
  last_name     VARCHAR(50) NOT NULL,
  gender        VARCHAR(10) NOT NULL,
  role          VARCHAR(50) NOT NULL,
  date_of_birth DATE,
  date_of_join  DATE,
  staff_mobile  VARCHAR(20) UNIQUE,
  staff_email   VARCHAR(120) UNIQUE
);

CREATE TABLE menu_items (
  menu_item_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id    INTEGER NOT NULL
                    REFERENCES categories(category_id)
                    ON UPDATE CASCADE ON DELETE RESTRICT,
  menu_item_name VARCHAR(100) NOT NULL,
  price          NUMERIC(7,2) NOT NULL CHECK (price >= 0)
);

-- ---------- Orders ----------
CREATE TABLE orders (
  order_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id        INTEGER NOT NULL
                    REFERENCES shops(shop_id)
                    ON UPDATE CASCADE ON DELETE RESTRICT,
  customer_id    INTEGER NOT NULL
                    REFERENCES customers(customer_id)
                    ON UPDATE CASCADE ON DELETE RESTRICT,
  payment_id     INTEGER
                    REFERENCES payment_methods(payment_id)
                    ON UPDATE CASCADE ON DELETE SET NULL,
  delivery_id    INTEGER
                    REFERENCES delivery_methods(delivery_id)
                    ON UPDATE CASCADE ON DELETE SET NULL,
  order_datetime TIMESTAMP NOT NULL,
  order_value    NUMERIC(10,2) CHECK (order_value >= 0)
);

CREATE TABLE order_items (
  order_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_item_id  INTEGER NOT NULL
                   REFERENCES menu_items(menu_item_id)
                   ON UPDATE CASCADE,
  order_id      INTEGER NOT NULL
                   REFERENCES orders(order_id)
                   ON UPDATE CASCADE ON DELETE CASCADE,
  quantity      INTEGER NOT NULL CHECK (quantity > 0),
  unit_price    NUMERIC(7,2) NOT NULL CHECK (unit_price >= 0),
  line_total    NUMERIC(10,2) NOT NULL
                   CHECK (line_total = ROUND(quantity * unit_price, 2))
);

-- ---------- Helpful indexes on FKs ----------
CREATE INDEX idx_customers_shop      ON customers(shop_id);
CREATE INDEX idx_staff_shop          ON staff(shop_id);
CREATE INDEX idx_menu_items_category ON menu_items(category_id);
CREATE INDEX idx_orders_shop         ON orders(shop_id);
CREATE INDEX idx_orders_customer     ON orders(customer_id);
CREATE INDEX idx_orders_payment      ON orders(payment_id);
CREATE INDEX idx_orders_delivery     ON orders(delivery_id);
CREATE INDEX idx_order_items_order   ON order_items(order_id);
CREATE INDEX idx_order_items_item    ON order_items(menu_item_id);
