-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categories
(
    category_id serial NOT NULL,
    category_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id),
    CONSTRAINT categories_category_name_key UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS public.menu_items
(
    category_id integer NOT NULL,
    menu_item_id integer NOT NULL,
    menu_item_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    price numeric(7, 2) NOT NULL,
    CONSTRAINT menu_items_pkey PRIMARY KEY (menu_item_id)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    order_item_id integer NOT NULL,
    menu_item_id integer NOT NULL,
    order_id integer NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(7, 2) NOT NULL,
    line_total numeric(10, 2) NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    shop_id integer NOT NULL,
    customer_id integer NOT NULL,
    order_id integer NOT NULL,
    order_datetime timestamp without time zone NOT NULL,
    payment_id integer,
    order_value numeric(10, 2),
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    shop_id integer,
    customer_id serial NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    mobile character varying(20) COLLATE pg_catalog."default",
    email character varying(120) COLLATE pg_catalog."default",
    gender character varying(10) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date NOT NULL,
    address character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT customers_pkey PRIMARY KEY (customer_id),
    CONSTRAINT customers_email_key UNIQUE (email),
    CONSTRAINT customers_mobile_key UNIQUE (mobile)
);

CREATE TABLE IF NOT EXISTS public.shops
(
    shop_id serial NOT NULL,
    shop_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    suburb character varying(50) COLLATE pg_catalog."default",
    postcode character(4) COLLATE pg_catalog."default" NOT NULL,
    state character(3) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT shops_pkey PRIMARY KEY (shop_id)
);

CREATE TABLE IF NOT EXISTS public.staff
(
    shop_id integer NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(10) COLLATE pg_catalog."default" NOT NULL,
    staff_id integer NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date,
    date_of_join date,
    staff_mobile character varying(20) COLLATE pg_catalog."default",
    staff_email character varying(120) COLLATE pg_catalog."default",
    CONSTRAINT staff_pkey PRIMARY KEY (staff_id),
    CONSTRAINT staff_staff_email_key UNIQUE (staff_email),
    CONSTRAINT staff_staff_mobile_key UNIQUE (staff_mobile)
);

CREATE TABLE IF NOT EXISTS public.payment_methods
(
    payment_id serial NOT NULL,
    payment_method_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT payment_methods_pkey PRIMARY KEY (payment_id),
    CONSTRAINT payment_methods_payment_method_name_key UNIQUE (payment_method_name)
);

ALTER TABLE IF EXISTS public.menu_items
    ADD CONSTRAINT menu_items_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.categories (category_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_menu_item_id_fkey FOREIGN KEY (menu_item_id)
    REFERENCES public.menu_items (menu_item_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_payment_id_fkey FOREIGN KEY (payment_id)
    REFERENCES public.payment_methods (payment_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_shop_id_fkey FOREIGN KEY (shop_id)
    REFERENCES public.shops (shop_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.customers
    ADD CONSTRAINT customers_shop_id_fkey FOREIGN KEY (shop_id)
    REFERENCES public.shops (shop_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.staff
    ADD CONSTRAINT staff_shop_id_fkey FOREIGN KEY (shop_id)
    REFERENCES public.shops (shop_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

END;